/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

/**
 *
 * @author Al Shariar
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;

public class hotel extends javax.swing.JFrame {

    /**
     * Creates new form hotel
     */
    Connection conn = null;
    Statement s=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public hotel() {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","root");
        }catch(Exception e){
            
        }
        initComponents();
        update_table();
        update_table2();
        currentdate();
        update_table3();
         Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }
    
    public void currentdate(){
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        lbldate.setText("Today's Date : "+year+"/"+(month+1)+"/"+day);
        int second=cal.get(Calendar.SECOND);
        int minute=cal.get(Calendar.MINUTE);
        int hour=cal.get(Calendar.HOUR);
        lbltime.setText(" Time : "+hour+":"+minute+":"+second);
    }
    
    private void update_table(){
        try{
            String sql="select * from information";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            
        }
    }
    private void update_table2(){
        try{
            String sql="select * from room";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jtable2.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            
        }
    }
    private void update_table3(){
        try{
            String sql="select * from worker";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jtable3.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lbltime = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jaddress2 = new javax.swing.JTextField();
        jsearchabout = new javax.swing.JTextField();
        jworkername = new javax.swing.JTextField();
        jmobilenumber = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtable3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jnumberofday = new javax.swing.JTextField();
        jcustomername = new javax.swing.JTextField();
        jaddress = new javax.swing.JTextField();
        jcity = new javax.swing.JTextField();
        jcountry = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jmaritalstatus = new javax.swing.JTextField();
        jnationality = new javax.swing.JTextField();
        jnationalidcardnumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jfrom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jto = new javax.swing.JTextField();
        clear_button = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jroomrent = new javax.swing.JTextField();
        jroomtype = new javax.swing.JTextField();
        jfloorno = new javax.swing.JTextField();
        jserial = new javax.swing.JTextField();
        jroomno = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable2 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jcustomername1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jaddress1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcity1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jcountry1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jphone1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jmaritalstatus1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jnationality1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jnationalidcardnumber1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jnumberofday1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jfrom1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jto1 = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        delete_buttom = new javax.swing.JButton();
        clear_button2 = new javax.swing.JButton();
        jsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Tutorial Manual");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 380, 90));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 100, 30));

        lbltime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltime.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 400, 50));

        lbldate.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbldate.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 400, 80));

        jButton15.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(51, 51, 255));
        jButton15.setText("Official website");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 190, 60));

        jButton17.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(51, 51, 255));
        jButton17.setText("Youtube Channel");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 190, 60));

        jButton18.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(51, 51, 255));
        jButton18.setText("Facebook page");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 190, 60));

        jTabbedPane1.addTab("Home", jPanel1);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 110, 30));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton13.setText("Clear");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton14.setText("Add Worker ");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton16.setText("Delete");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel27.setText("Address :");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 30));

        jLabel28.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel28.setText("Search :");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 30));

        jLabel29.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel29.setText("Worker Name :");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, 30));

        jLabel30.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel30.setText("Mobile_Number :");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, 30));
        jPanel4.add(jaddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 170, 30));

        jsearchabout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsearchaboutKeyPressed(evt);
            }
        });
        jPanel4.add(jsearchabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 170, 40));
        jPanel4.add(jworkername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, 30));
        jPanel4.add(jmobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 170, 30));

        jtable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable3MouseClicked(evt);
            }
        });
        jtable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtable3KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jtable3);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 10, 520, 390));

        jTabbedPane1.addTab("About", jPanel4);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Customer Name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Address :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, 30));

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("City / Town :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 30));

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Country :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 30));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Phone :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 30));

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Maritul Status :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 30));

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Nationality :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, 30));

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("National Id card Number :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 30));

        jLabel11.setBackground(new java.awt.Color(204, 255, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Departure time :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 170, 30));
        jPanel2.add(jnumberofday, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 220, 30));
        jPanel2.add(jcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 220, 30));
        jPanel2.add(jaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 220, 30));
        jPanel2.add(jcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 220, 30));
        jPanel2.add(jcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 220, 30));
        jPanel2.add(jphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 220, 30));
        jPanel2.add(jmaritalstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 220, 30));
        jPanel2.add(jnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 220, 30));

        jnationalidcardnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnationalidcardnumberActionPerformed(evt);
            }
        });
        jPanel2.add(jnationalidcardnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 220, 30));

        jLabel12.setBackground(new java.awt.Color(204, 255, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Number of day :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 170, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("From :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 60, 20));

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 255));
        jButton1.setText("Save");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 130, 40));
        jPanel2.add(jfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 170, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("To :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));
        jPanel2.add(jto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 150, 40));

        clear_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear_button.setText("Clear");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(clear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 130, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 130, 30));

        jTabbedPane1.addTab("Room Booking", jPanel2);

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Room Information");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jButton9.setText("Room type");
        jPanel7.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, 30));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setText("Add Room");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));
        jPanel7.add(jroomrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, 30));
        jPanel7.add(jroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, 30));
        jPanel7.add(jfloorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 110, 30));
        jPanel7.add(jserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 110, 30));
        jPanel7.add(jroomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 110, 30));

        jLabel31.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel31.setText("Room Rent :");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 160, 20));

        jtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable2);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 540, 460));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setText("Delete Room");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 423, -1, 30));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setText("Clear");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 383, 80, 30));

        jLabel35.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel35.setText("Serial :");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 20));

        jLabel36.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel36.setText("Room No :");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, 20));

        jLabel37.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel37.setText("Room Type:");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 20));

        jLabel38.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel38.setText("Floor No :");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 20));

        jTabbedPane1.addTab("status", jPanel7);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        table1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 700, 460));

        jLabel14.setBackground(new java.awt.Color(204, 255, 204));
        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Customer Name :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));
        jPanel3.add(jcustomername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 220, 30));

        jLabel15.setBackground(new java.awt.Color(204, 255, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Address :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, 30));
        jPanel3.add(jaddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 220, 30));

        jLabel16.setBackground(new java.awt.Color(204, 255, 204));
        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("City / Town :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 30));
        jPanel3.add(jcity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 220, 30));

        jLabel17.setBackground(new java.awt.Color(204, 255, 204));
        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("Country :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 30));
        jPanel3.add(jcountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 220, 30));

        jLabel18.setBackground(new java.awt.Color(204, 255, 204));
        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("Phone :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 30));
        jPanel3.add(jphone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 220, 30));

        jLabel19.setBackground(new java.awt.Color(204, 255, 204));
        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("Maritul Status :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 30));
        jPanel3.add(jmaritalstatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 220, 30));

        jLabel20.setBackground(new java.awt.Color(204, 255, 204));
        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Nationality :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, 30));
        jPanel3.add(jnationality1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 220, 30));

        jLabel21.setBackground(new java.awt.Color(204, 255, 204));
        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("National Id card Number :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 30));

        jnationalidcardnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnationalidcardnumber1ActionPerformed(evt);
            }
        });
        jPanel3.add(jnationalidcardnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 220, 30));

        jLabel22.setBackground(new java.awt.Color(204, 255, 204));
        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("Number of day :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 170, 30));
        jPanel3.add(jnumberofday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 220, 30));

        jLabel23.setBackground(new java.awt.Color(204, 255, 204));
        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 153));
        jLabel23.setText("Departure time :");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 170, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("From :");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 60, 20));
        jPanel3.add(jfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 170, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("To :");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));
        jPanel3.add(jto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 150, 40));

        update_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 100, 30));

        delete_buttom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_buttom.setText("Delete");
        delete_buttom.setToolTipText("Delete customer information");
        delete_buttom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttomActionPerformed(evt);
            }
        });
        jPanel3.add(delete_buttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        clear_button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear_button2.setText("Clear");
        clear_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_button2ActionPerformed(evt);
            }
        });
        jPanel3.add(clear_button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        jsearch.setToolTipText("Search customer information");
        jsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jsearchKeyReleased(evt);
            }
        });
        jPanel3.add(jsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Search :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Exit");
        jButton4.setToolTipText("Exit this software");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 90, 30));

        jTabbedPane1.addTab("Update", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnationalidcardnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnationalidcardnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnationalidcardnumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String customername=jcustomername.getText();
        String address=jaddress.getText();
        String city=jcity.getText();
        String country=jcountry.getText();
        String phone =jphone.getText();
        String maritalstatus=jmaritalstatus.getText();
        String nationality=jnationality.getText();
        String nationalidcardnumber=jnationalidcardnumber.getText();
        String numberofday=jnumberofday.getText();
        String from=jfrom.getText();
        String to=jto.getText();

        try{
            
            conn.createStatement();

            String qu="insert into information "
            +"values('"+customername+"','"+address+"','"+city+"','"+country+"','"+phone+"','"+maritalstatus+"','"+nationality+"','"+nationalidcardnumber+"','"+numberofday+"','"+from+"','"+to+"')";
            s=conn.createStatement();
            // JOptionPane.showMessageDialog(null, "Database is Connected");
            s.executeUpdate(qu);
            JOptionPane.showMessageDialog(null, "Save data successsfully");

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
        update_table();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jnationalidcardnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnationalidcardnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnationalidcardnumber1ActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        
        try{
            int row=table1.getSelectedRow();
            String table_click=(table1.getModel().getValueAt(row, 0).toString());
            String sql="select*from information where Customer_Name='"+table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Customer_Name");
                jcustomername1.setText(add1);
                 String add2=rs.getString("Address");
                jaddress1.setText(add2);
                 String add3=rs.getString("City");
                jcity1.setText(add3);
                 String add4=rs.getString("Country");
                jcountry1.setText(add4);
                 String add5=rs.getString("Phone");
                jphone1.setText(add5);
                 String add6=rs.getString("Marital_Status");
                jmaritalstatus1.setText(add6);
                 String add7=rs.getString("Nationality");
                jnationality1.setText(add7);
                 String add8=rs.getString("National_Id_Card_No");
                jnationalidcardnumber1.setText(add8);
                 String add9=rs.getString("No_Of_Day");
                jnumberofday1.setText(add9);
                 String add10=rs.getString("Departure_From");
                jfrom1.setText(add10);
                 String add11=rs.getString("Arrived_To");
                jto1.setText(add11);
                
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_table1MouseClicked

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
       try{ String value1=jcustomername1.getText();
        String value2=jaddress1.getText();
        String value3=jcity1.getText();
        String value4=jcountry1.getText();
        String value5=jphone1.getText();
        String value6=jmaritalstatus1.getText();
        
                String value7=jnationality1.getText();
                String value8=jnationalidcardnumber1.getText();
                        String value9=jnumberofday1.getText();
                        String value10=jfrom1.getText();
                        String value11=jto1.getText();
                        String sq="update information set Customer_Name='"+value1+"', Address='"+value2+"',City='"+value3+"',Country='"+value4+"',Phone='"+value5+"',Marital_Status='"+value6+"',Nationality='"+value7+"',National_Id_Card_No='"+value8+"',No_Of_Day='"+value9+"',Departure_From='"+value10+"', To='"+value11+"'  where  Customer_Name='"+value1+"'";
                        pst=conn.prepareStatement(sq);
                        pst.execute();
        JOptionPane.showMessageDialog(null, "Updated");
       }
        
       catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
       }
       update_table();
    }//GEN-LAST:event_update_buttonActionPerformed

    private void delete_buttomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttomActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null, "Are you want to delete it ? ","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
        String sql="delete from information where Customer_Name=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,jcustomername1.getText());
            pst.execute();
             JOptionPane.showMessageDialog(null, "Deleted");
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
        update_table();
        }
    }//GEN-LAST:event_delete_buttomActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        jcustomername.setText(null);
         jaddress.setText(null);
       jcity.setText(null);
        jcountry.setText(null);
       jphone.setText(null);
        jmaritalstatus.setText(null);
        jnationality.setText(null);
        jnationalidcardnumber.setText(null);
        jnumberofday.setText(null);
        jfrom.setText(null);
        jto.setText(null);
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void clear_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_button2ActionPerformed
        // TODO add your handling code here:
        jcustomername1.setText(null);
         jaddress1.setText(null);
       jcity1.setText(null);
        jcountry1.setText(null);
       jphone1.setText(null);
        jmaritalstatus1.setText(null);
        jnationality1.setText(null);
        jnationalidcardnumber1.setText(null);
        jnumberofday1.setText(null);
        jfrom1.setText(null);
        jto1.setText(null);
    }//GEN-LAST:event_clear_button2ActionPerformed

    private void jsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsearchKeyReleased
      try{
          String sql="select *from information where phone=?";
          pst=conn.prepareStatement(sql);
          pst.setString(1, jsearch.getText());
          rs=pst.executeQuery();
          if(rs.next()){
             String add1=rs.getString("Customer_Name");
                jcustomername1.setText(add1);
                 String add2=rs.getString("Address");
                jaddress1.setText(add2);
                 String add3=rs.getString("City");
                jcity1.setText(add3);
                 String add4=rs.getString("Country");
                jcountry1.setText(add4);
                 String add5=rs.getString("Phone");
                jphone1.setText(add5);
                 String add6=rs.getString("Marital_Status");
                jmaritalstatus1.setText(add6);
                 String add7=rs.getString("Nationality");
                jnationality1.setText(add7);
                 String add8=rs.getString("National_Id_Card_No");
                jnationalidcardnumber1.setText(add8);
                 String add9=rs.getString("No_Of_Day");
                jnumberofday1.setText(add9);
                 String add10=rs.getString("Departure_From");
                jfrom1.setText(add10);
                 String add11=rs.getString("To");
                jto1.setText(add11);
          }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
      try{
          String sql="select *from information where Customer_Name=?";
          pst=conn.prepareStatement(sql);
          pst.setString(1, jsearch.getText());
          rs=pst.executeQuery();
          if(rs.next()){
             String add1=rs.getString("Customer_Name");
                jcustomername1.setText(add1);
                 String add2=rs.getString("Address");
                jaddress1.setText(add2);
                 String add3=rs.getString("City");
                jcity1.setText(add3);
                 String add4=rs.getString("Country");
                jcountry1.setText(add4);
                 String add5=rs.getString("Phone");
                jphone1.setText(add5);
                 String add6=rs.getString("Marital_Status");
                jmaritalstatus1.setText(add6);
                 String add7=rs.getString("Nationality");
                jnationality1.setText(add7);
                 String add8=rs.getString("National_Id_Card_No");
                jnationalidcardnumber1.setText(add8);
                 String add9=rs.getString("No_Of_Day");
                jnumberofday1.setText(add9);
                 String add10=rs.getString("Departure_From");
                jfrom1.setText(add10);
                 String add11=rs.getString("To");
                jto1.setText(add11);
          }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
    }//GEN-LAST:event_jsearchKeyReleased

    private void table1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN ||evt.getKeyCode()==KeyEvent.VK_UP){
             try{
            int row=table1.getSelectedRow();
            String table_click=(table1.getModel().getValueAt(row, 0).toString());
            String sql="select*from information where Customer_Name='"+table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Customer_Name");
                jcustomername1.setText(add1);
                 String add2=rs.getString("Address");
                jaddress1.setText(add2);
                 String add3=rs.getString("City");
                jcity1.setText(add3);
                 String add4=rs.getString("Country");
                jcountry1.setText(add4);
                 String add5=rs.getString("Phone");
                jphone1.setText(add5);
                 String add6=rs.getString("Marital_Status");
                jmaritalstatus1.setText(add6);
                 String add7=rs.getString("Nationality");
                jnationality1.setText(add7);
                 String add8=rs.getString("National_Id_Card_No");
                jnationalidcardnumber1.setText(add8);
                 String add9=rs.getString("No_Of_Day");
                jnumberofday1.setText(add9);
                 String add10=rs.getString("Departure_From");
                jfrom1.setText(add10);
                 String add11=rs.getString("To");
                jto1.setText(add11);
                
            }
        }catch(Exception e){
            
        }
        }
    }//GEN-LAST:event_table1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"E:\\cp project\\ticket-provider.pdf");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int p=JOptionPane.showConfirmDialog(null, "Are you want to exit it ? ","Exit",JOptionPane.YES_NO_OPTION);
        if(p==0){
        System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null, "Are you want to exit it ? ","Exit",JOptionPane.YES_NO_OPTION);
        if(p==0){
        System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null, "Are you want to exit it ? ","Exit",JOptionPane.YES_NO_OPTION);
        if(p==0){
        System.exit(0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null, "Are you want to exit it ? ","Exit",JOptionPane.YES_NO_OPTION);
        if(p==0){
        System.exit(0);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null, "Are you want to exit it ? ","Exit",JOptionPane.YES_NO_OPTION);
        if(p==0){
        System.exit(0);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String serial=jserial.getText();
        String roomno=jroomno.getText();
        String roomtype=jroomtype.getText();
        String floorno=jfloorno.getText();
        String roomrent=jroomrent.getText();
        

        try{
            
            

            String qlu="insert into room values('"+serial+"','"+roomno+"','"+roomtype+"','"+floorno+"','"+roomrent+"')";
            s=conn.createStatement();
            // JOptionPane.showMessageDialog(null, "Database is Connected");
            s.executeUpdate(qlu);
            JOptionPane.showMessageDialog(null, "Save data successsfully");

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
        update_table2();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         int p=JOptionPane.showConfirmDialog(null, "Are you want to delete it ? ","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
        String sql="delete from room where Serial=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,jserial.getText());
            pst.execute();
             JOptionPane.showMessageDialog(null, "Deleted");
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
        update_table2();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jtable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable2MouseClicked
        // TODO add your handling code here:
         try{
            int row=jtable2.getSelectedRow();
            String table_click=(jtable2.getModel().getValueAt(row, 0).toString());
            String sql="select*from room where Serial='"+table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Serial");
                jserial.setText(add1);
                 String add2=rs.getString("Room_No");
                jroomno.setText(add2);
                 String add3=rs.getString("Room_Type");
                jroomtype.setText(add3);
                 String add4=rs.getString("Floor_No");
                jfloorno.setText(add4);
                 String add5=rs.getString("Room_Rent");
                jroomrent.setText(add5);
                 
                
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jtable2MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jserial.setText(null);
         jroomno.setText(null);
       jroomtype.setText(null);
        jfloorno.setText(null);
       jroomrent.setText(null);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        String workername=jworkername.getText();
        String mobilenumber=jmobilenumber.getText();
        String address2=jaddress2.getText();
       
        

        try{
            
            

            String qlu="insert into worker values('"+workername+"','"+mobilenumber+"','"+address2+"')";
            s=conn.createStatement();
            // JOptionPane.showMessageDialog(null, "Database is Connected");
            s.executeUpdate(qlu);
            JOptionPane.showMessageDialog(null, "Save data successsfully");

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
        update_table3();
    }//GEN-LAST:event_jButton14ActionPerformed
// clear button for about window
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         jworkername.setText(null);
         jmobilenumber.setText(null);
       jaddress2.setText(null);
       jsearchabout.setText(null);
        
    }//GEN-LAST:event_jButton13ActionPerformed

// Abot window table_click for show in the Jtext Field


    private void jtable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable3MouseClicked
        // TODO add your handling code here:
        try{
            int row=jtable3.getSelectedRow();
            String table_click=(jtable3.getModel().getValueAt(row, 0).toString());
            String sql="select*from worker where Worker_Name='"+table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Worker_Name");
                jworkername.setText(add1);
                 String add2=rs.getString("Phone");
                jmobilenumber.setText(add2);
                 String add3=rs.getString("Address");
                jaddress2.setText(add3);
                 
                 
                
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jtable3MouseClicked

    // delete button for About windows
    
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        
          int p=JOptionPane.showConfirmDialog(null, "Are you want to delete it ? ","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
        String sql="delete from worker where Worker_Name=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,jworkername.getText());
            pst.execute();
             JOptionPane.showMessageDialog(null, "Deleted");
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
        update_table3();
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jsearchaboutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsearchaboutKeyPressed
        // TODO add your handling code here:
        try{
          String sql="select *from worker where Worker_Name=?";
          pst=conn.prepareStatement(sql);
          pst.setString(1, jsearchabout.getText());
          rs=pst.executeQuery();
          if(rs.next()){
             String add1=rs.getString("Worker_Name");
                jworkername.setText(add1);
                 String add2=rs.getString("Phone");
                jmobilenumber.setText(add2);
                 String add3=rs.getString("Address");
                jaddress2.setText(add3);
                
          }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
      try{
          String sql="select *from worker where Phone=?";
          pst=conn.prepareStatement(sql);
          pst.setString(1, jsearchabout.getText());
          rs=pst.executeQuery();
          if(rs.next()){
             String add1=rs.getString("Worker_Name");
                jworkername.setText(add1);
                 String add2=rs.getString("Phone");
                jmobilenumber.setText(add2);
                 String add3=rs.getString("Address");
                jaddress2.setText(add3);
                 
      }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
              }
      
    }//GEN-LAST:event_jsearchaboutKeyPressed

    private void jtable3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtable3KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_DOWN ||evt.getKeyCode()==KeyEvent.VK_UP){
             try{
            int row=jtable3.getSelectedRow();
            String table_click=(jtable3.getModel().getValueAt(row, 0).toString());
            String sql="select*from worker where Worker_Name='"+table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Worker_Name");
                jworkername.setText(add1);
                 String add2=rs.getString("Phone");
                jmobilenumber.setText(add2);
                 String add3=rs.getString("Address");
                jaddress2.setText(add3);
                
             
            }
        }catch(Exception e){
            
        }
        }
    }//GEN-LAST:event_jtable3KeyPressed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        try{
            String url1="https://www.youtube.com/channel/UCOnIvQVhGDpkITlbXvlIX7w/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url1));
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        try{
            String url1="https://www.facebook.com/profile.php?id=100004930505214/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url1));
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         try{
            String url1="http://10minuteschool.com/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url1));
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_button;
    private javax.swing.JButton clear_button2;
    private javax.swing.JButton delete_buttom;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jaddress;
    private javax.swing.JTextField jaddress1;
    private javax.swing.JTextField jaddress2;
    private javax.swing.JTextField jcity;
    private javax.swing.JTextField jcity1;
    private javax.swing.JTextField jcountry;
    private javax.swing.JTextField jcountry1;
    private javax.swing.JTextField jcustomername;
    private javax.swing.JTextField jcustomername1;
    private javax.swing.JTextField jfloorno;
    private javax.swing.JTextField jfrom;
    private javax.swing.JTextField jfrom1;
    private javax.swing.JTextField jmaritalstatus;
    private javax.swing.JTextField jmaritalstatus1;
    private javax.swing.JTextField jmobilenumber;
    private javax.swing.JTextField jnationalidcardnumber;
    private javax.swing.JTextField jnationalidcardnumber1;
    private javax.swing.JTextField jnationality;
    private javax.swing.JTextField jnationality1;
    private javax.swing.JTextField jnumberofday;
    private javax.swing.JTextField jnumberofday1;
    private javax.swing.JTextField jphone;
    private javax.swing.JTextField jphone1;
    private javax.swing.JTextField jroomno;
    private javax.swing.JTextField jroomrent;
    private javax.swing.JTextField jroomtype;
    private javax.swing.JTextField jsearch;
    private javax.swing.JTextField jsearchabout;
    private javax.swing.JTextField jserial;
    private javax.swing.JTable jtable2;
    private javax.swing.JTable jtable3;
    private javax.swing.JTextField jto;
    private javax.swing.JTextField jto1;
    private javax.swing.JTextField jworkername;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTable table1;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
