/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_user;

/**
 *
 * @author Al Shariar
 */
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
public class CustomerBooking extends javax.swing.JFrame {

    /**
     * Creates new form CustomerBooking
     */
    Connection conn=JdbcConnect.connect();
    PreparedStatement pst=null;
    Statement s=null;
    ResultSet rs=null;
    public CustomerBooking() {
        initComponents();
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jnumberofday = new javax.swing.JTextField();
        jcustomername = new javax.swing.JTextField();
        jaddress = new javax.swing.JTextField();
        jcity = new javax.swing.JTextField();
        jcountry = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jmaritalstatus = new javax.swing.JTextField();
        jnationality = new javax.swing.JTextField();
        jnationalidcardnumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jfrom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jto = new javax.swing.JTextField();
        clear_button = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Customer Name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Address :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, 30));

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("City / Town :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 30));

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Country :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 30));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Phone :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 30));

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Maritul Status :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 30));

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Nationality :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, 30));

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("National Id card Number :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 30));

        jLabel11.setBackground(new java.awt.Color(204, 255, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Departure time :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 170, 30));
        jPanel2.add(jnumberofday, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 220, 30));
        jPanel2.add(jcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 220, 30));
        jPanel2.add(jaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 220, 30));
        jPanel2.add(jcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 220, 30));
        jPanel2.add(jcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 220, 30));
        jPanel2.add(jphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 220, 30));
        jPanel2.add(jmaritalstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 220, 30));
        jPanel2.add(jnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 220, 30));

        jnationalidcardnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnationalidcardnumberActionPerformed(evt);
            }
        });
        jPanel2.add(jnationalidcardnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 220, 30));

        jLabel12.setBackground(new java.awt.Color(204, 255, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Number of day :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 170, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("From :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 60, 20));

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 255));
        jButton1.setText("Save");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 130, 40));
        jPanel2.add(jfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 170, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("To :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));
        jPanel2.add(jto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 150, 40));

        clear_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear_button.setText("Clear");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(clear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 130, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnationalidcardnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnationalidcardnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnationalidcardnumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String customername=jcustomername.getText();
        String address=jaddress.getText();
        String city=jcity.getText();
        String country=jcountry.getText();
        String phone =jphone.getText();
        String maritalstatus=jmaritalstatus.getText();
        String nationality=jnationality.getText();
        String nationalidcardnumber=jnationalidcardnumber.getText();
        String numberofday=jnumberofday.getText();
        String from=jfrom.getText();
        String to=jto.getText();

        try{

            conn.createStatement();

            String qu="insert into information "
            +"values('"+customername+"','"+address+"','"+city+"','"+country+"','"+phone+"','"+maritalstatus+"','"+nationality+"','"+nationalidcardnumber+"','"+numberofday+"','"+from+"','"+to+"')";
            s=conn.createStatement();
            // JOptionPane.showMessageDialog(null, "Database is Connected");
            s.executeUpdate(qu);
            JOptionPane.showMessageDialog(null, "Save data successsfully");
            

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        jcustomername.setText(null);
        jaddress.setText(null);
        jcity.setText(null);
        jcountry.setText(null);
        jphone.setText(null);
        jmaritalstatus.setText(null);
        jnationality.setText(null);
        jnationalidcardnumber.setText(null);
        jnumberofday.setText(null);
        jfrom.setText(null);
        jto.setText(null);
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
           UserLanding userLanding=new UserLanding();
           userLanding.setVisible(true);
           this.dispose();
       
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jaddress;
    private javax.swing.JTextField jcity;
    private javax.swing.JTextField jcountry;
    private javax.swing.JTextField jcustomername;
    private javax.swing.JTextField jfrom;
    private javax.swing.JTextField jmaritalstatus;
    private javax.swing.JTextField jnationalidcardnumber;
    private javax.swing.JTextField jnationality;
    private javax.swing.JTextField jnumberofday;
    private javax.swing.JTextField jphone;
    private javax.swing.JTextField jto;
    // End of variables declaration//GEN-END:variables
}
