/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package admin_user;
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Al Shariar
 */
public class UpdateCustomer extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCustomer
     */
    Connection conn=JdbcConnect.connect();
    PreparedStatement pst=null;
    Statement s=null;
    ResultSet rs=null;
    public UpdateCustomer() {
        initComponents();
        updateAllCustomer();
    }
    private void updateAllCustomer(){
        Connection conn=JdbcConnect.connect();
        
         try{
            String sql="select * from hotel.information";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jcustomername1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jaddress1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcity1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jcountry1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jphone1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jmaritalstatus1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jnationality1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jnationalidcardnumber1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jnumberofday1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jfrom1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jto1 = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        delete_buttom = new javax.swing.JButton();
        clear_button2 = new javax.swing.JButton();
        jsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        table1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 760, 460));

        jLabel14.setBackground(new java.awt.Color(204, 255, 204));
        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Customer Name :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));
        jPanel3.add(jcustomername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 220, 30));

        jLabel15.setBackground(new java.awt.Color(204, 255, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Address :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, 30));
        jPanel3.add(jaddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 220, 30));

        jLabel16.setBackground(new java.awt.Color(204, 255, 204));
        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("City / Town :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 30));
        jPanel3.add(jcity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 220, 30));

        jLabel17.setBackground(new java.awt.Color(204, 255, 204));
        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("Country :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 30));
        jPanel3.add(jcountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 220, 30));

        jLabel18.setBackground(new java.awt.Color(204, 255, 204));
        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("Phone :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 30));
        jPanel3.add(jphone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 220, 30));

        jLabel19.setBackground(new java.awt.Color(204, 255, 204));
        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("Maritul Status :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 30));
        jPanel3.add(jmaritalstatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 220, 30));

        jLabel20.setBackground(new java.awt.Color(204, 255, 204));
        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Nationality :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, 30));
        jPanel3.add(jnationality1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 220, 30));

        jLabel21.setBackground(new java.awt.Color(204, 255, 204));
        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("National Id card Number :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 30));

        jnationalidcardnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnationalidcardnumber1ActionPerformed(evt);
            }
        });
        jPanel3.add(jnationalidcardnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 220, 30));

        jLabel22.setBackground(new java.awt.Color(204, 255, 204));
        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("Number of day :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 170, 30));
        jPanel3.add(jnumberofday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 220, 30));

        jLabel23.setBackground(new java.awt.Color(204, 255, 204));
        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 153));
        jLabel23.setText("Departure time :");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 170, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("From :");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 60, 20));
        jPanel3.add(jfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 170, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("To :");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));
        jPanel3.add(jto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 150, 40));

        update_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 100, 30));

        delete_buttom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_buttom.setText("Delete");
        delete_buttom.setToolTipText("Delete customer information");
        delete_buttom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttomActionPerformed(evt);
            }
        });
        jPanel3.add(delete_buttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        clear_button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear_button2.setText("Clear");
        clear_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_button2ActionPerformed(evt);
            }
        });
        jPanel3.add(clear_button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        jsearch.setToolTipText("Search customer information");
        jsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jsearchKeyReleased(evt);
            }
        });
        jPanel3.add(jsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Search :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.setToolTipText("Exit this software");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1336, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1326, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:

        try{
            int row=table1.getSelectedRow();
            String table_click=(table1.getModel().getValueAt(row, 0).toString());
            String sql="select*from information where Customer_Name='"+table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Customer_Name");
                jcustomername1.setText(add1);
                String add2=rs.getString("Address");
                jaddress1.setText(add2);
                String add3=rs.getString("City");
                jcity1.setText(add3);
                String add4=rs.getString("Country");
                jcountry1.setText(add4);
                String add5=rs.getString("Phone");
                jphone1.setText(add5);
                String add6=rs.getString("Marital_Status");
                jmaritalstatus1.setText(add6);
                String add7=rs.getString("Nationality");
                jnationality1.setText(add7);
                String add8=rs.getString("National_Id_Card_No");
                jnationalidcardnumber1.setText(add8);
                String add9=rs.getString("No_Of_Day");
                jnumberofday1.setText(add9);
                String add10=rs.getString("Departure_From");
                jfrom1.setText(add10);
                String add11=rs.getString("Arrived_To");
                jto1.setText(add11);

            }
        }catch(Exception e){

        }
    }//GEN-LAST:event_table1MouseClicked

    private void table1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN ||evt.getKeyCode()==KeyEvent.VK_UP){
            try{
                int row=table1.getSelectedRow();
                String table_click=(table1.getModel().getValueAt(row, 0).toString());
                String sql="select*from information where Customer_Name='"+table_click+"' ";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    String add1=rs.getString("Customer_Name");
                    jcustomername1.setText(add1);
                    String add2=rs.getString("Address");
                    jaddress1.setText(add2);
                    String add3=rs.getString("City");
                    jcity1.setText(add3);
                    String add4=rs.getString("Country");
                    jcountry1.setText(add4);
                    String add5=rs.getString("Phone");
                    jphone1.setText(add5);
                    String add6=rs.getString("Marital_Status");
                    jmaritalstatus1.setText(add6);
                    String add7=rs.getString("Nationality");
                    jnationality1.setText(add7);
                    String add8=rs.getString("National_Id_Card_No");
                    jnationalidcardnumber1.setText(add8);
                    String add9=rs.getString("No_Of_Day");
                    jnumberofday1.setText(add9);
                    String add10=rs.getString("Departure_From");
                    jfrom1.setText(add10);
                    String add11=rs.getString("To");
                    jto1.setText(add11);

                }
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_table1KeyPressed

    private void jnationalidcardnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnationalidcardnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnationalidcardnumber1ActionPerformed
//-------------------------Update Button-------------------------------
    
    
    
    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        try{ String value1=jcustomername1.getText();
            String value2=jaddress1.getText();
            String value3=jcity1.getText();
            String value4=jcountry1.getText();
            String value5=jphone1.getText();
            String value6=jmaritalstatus1.getText();

            String value7=jnationality1.getText();
            String value8=jnationalidcardnumber1.getText();
            String value9=jnumberofday1.getText();
            String value10=jfrom1.getText();
            String value11=jto1.getText();
            String sq="update information set Customer_Name='"+value1+"', Address='"+value2+"',City='"+value3+"',Country='"+value4+"',Phone='"+value5+"',Marital_Status='"+value6+"',Nationality='"+value7+"',National_Id_Card_No='"+value8+"',No_Of_Day='"+value9+"',Departure_From='"+value10+"', To='"+value11+"'  where  Customer_Name='"+value1+"'";
            pst=conn.prepareStatement(sq);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        updateAllCustomer();
    }//GEN-LAST:event_update_buttonActionPerformed

    
    //----------------------------Delete Button------------------------------
    
    
    private void delete_buttomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttomActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null, "Are you want to delete it ? ","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String sql="delete from information where Customer_Name=?";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1,jcustomername1.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            updateAllCustomer();
        }
    }//GEN-LAST:event_delete_buttomActionPerformed
//--------------------------Clear Button---------------------------
    
    
    private void clear_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_button2ActionPerformed
        // TODO add your handling code here:
        jcustomername1.setText(null);
        jaddress1.setText(null);
        jcity1.setText(null);
        jcountry1.setText(null);
        jphone1.setText(null);
        jmaritalstatus1.setText(null);
        jnationality1.setText(null);
        jnationalidcardnumber1.setText(null);
        jnumberofday1.setText(null);
        jfrom1.setText(null);
        jto1.setText(null);
    }//GEN-LAST:event_clear_button2ActionPerformed

    //------------------------Search--------------------------------
    
    
    private void jsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsearchKeyReleased
        try{
            String sql="select *from information where phone=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, jsearch.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Customer_Name");
                jcustomername1.setText(add1);
                String add2=rs.getString("Address");
                jaddress1.setText(add2);
                String add3=rs.getString("City");
                jcity1.setText(add3);
                String add4=rs.getString("Country");
                jcountry1.setText(add4);
                String add5=rs.getString("Phone");
                jphone1.setText(add5);
                String add6=rs.getString("Marital_Status");
                jmaritalstatus1.setText(add6);
                String add7=rs.getString("Nationality");
                jnationality1.setText(add7);
                String add8=rs.getString("National_Id_Card_No");
                jnationalidcardnumber1.setText(add8);
                String add9=rs.getString("No_Of_Day");
                jnumberofday1.setText(add9);
                String add10=rs.getString("Departure_From");
                jfrom1.setText(add10);
                String add11=rs.getString("To");
                jto1.setText(add11);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        try{
            String sql="select *from information where Customer_Name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, jsearch.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Customer_Name");
                jcustomername1.setText(add1);
                String add2=rs.getString("Address");
                jaddress1.setText(add2);
                String add3=rs.getString("City");
                jcity1.setText(add3);
                String add4=rs.getString("Country");
                jcountry1.setText(add4);
                String add5=rs.getString("Phone");
                jphone1.setText(add5);
                String add6=rs.getString("Marital_Status");
                jmaritalstatus1.setText(add6);
                String add7=rs.getString("Nationality");
                jnationality1.setText(add7);
                String add8=rs.getString("National_Id_Card_No");
                jnationalidcardnumber1.setText(add8);
                String add9=rs.getString("No_Of_Day");
                jnumberofday1.setText(add9);
                String add10=rs.getString("Departure_From");
                jfrom1.setText(add10);
                String add11=rs.getString("To");
                jto1.setText(add11);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jsearchKeyReleased
//-------------------------exit button----------------------------
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        UserLanding userLanding=new UserLanding();
        userLanding.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_button2;
    private javax.swing.JButton delete_buttom;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jaddress1;
    private javax.swing.JTextField jcity1;
    private javax.swing.JTextField jcountry1;
    private javax.swing.JTextField jcustomername1;
    private javax.swing.JTextField jfrom1;
    private javax.swing.JTextField jmaritalstatus1;
    private javax.swing.JTextField jnationalidcardnumber1;
    private javax.swing.JTextField jnationality1;
    private javax.swing.JTextField jnumberofday1;
    private javax.swing.JTextField jphone1;
    private javax.swing.JTextField jsearch;
    private javax.swing.JTextField jto1;
    private javax.swing.JTable table1;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
